import type { DefaultTheme } from "vitepress";

/** Auto-generated by scripts/generate-api-docs.mjs — do not edit by hand. */
export const apiSidebar: DefaultTheme.SidebarItem[] = [
  {
    text: "API Reference",
    items: [{ text: "Overview", link: "/api/" }],
  },
  {
    text: "Packages",
    collapsed: false,
    items: [
      { text: "@stambha/core", link: "/api/core/" },
      { text: "@stambha/loader", link: "/api/loader/" },
      { text: "@stambha/gates", link: "/api/gates/" },
      { text: "@stambha/vault", link: "/api/vault/" },
      { text: "@stambha/rest", link: "/api/rest/" },
      { text: "@stambha/gateway", link: "/api/gateway/" },
      { text: "@stambha/transform", link: "/api/transform/" },
      { text: "@stambha/args", link: "/api/args/" },
      { text: "@stambha/authz", link: "/api/authz/" },
      { text: "@stambha/plugins", link: "/api/plugins/" },
      { text: "@stambha/help", link: "/api/help/" },
      { text: "@stambha/transport", link: "/api/transport/" },
    ],
  },
  {
    text: "Related",
    items: [
      { text: "Transport map", link: "/reference/transport" },
      {
        text: "Package source on GitHub",
        link: "https://github.com/mivaya/Stambha/tree/main/packages",
        process: false,
      },
    ],
  },
];
